import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Ensure header reflects session immediately after auth changes
export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  let user: { id?: string, email?: string } | null = null
  let hasCC = false
  try {
    const { getSupabaseServer } = await import('@/lib/supabase-server')
    const supabase = await getSupabaseServer()
    const { data } = await supabase.auth.getUser()
    user = data?.user ?? null
    // Resolve CC role for nav visibility
    if (user?.id) {
      const { data: appUser } = await supabase
        .from('users')
        .select('id')
        .eq('auth_uid', user.id)
        .maybeSingle()
      const appUserId = appUser?.id as string | undefined
      if (appUserId) {
        const { data: roles } = await supabase
          .from('user_roles')
          .select('role_id')
          .eq('user_id', appUserId)
        hasCC = Array.isArray(roles) && roles.some(r => r.role_id === 'CC')
      }
    }
  } catch {
    // Supabase not configured; render public nav only
  }

  async function logout() {
    'use server'
    const { cookies } = await import('next/headers')
    const { redirect } = await import('next/navigation')
    const store = await cookies()
    store.delete('sb-access-token')
    store.delete('sb-refresh-token')
    try {
      const { getSupabaseServer } = await import('@/lib/supabase-server')
      const supabase = await getSupabaseServer()
      await supabase.auth.signOut()
    } catch {}
    redirect('/login')
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-50 dark:bg-zinc-900`}>
        <header className="border-b bg-white">
          <nav className="mx-auto max-w-6xl px-4 py-3 w-full flex items-center justify-between">
            <Link href="/" className="font-semibold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600">EduSync</Link>
            <ul className="flex gap-4 text-sm items-center">
              {user && hasCC && (
                <>
                  <li><Link href="/violation-entry">Nhập vi phạm</Link></li>
                  <li><Link href="/score-entry">Nhập điểm</Link></li>
                </>
              )}
              {!user ? (
                <li><Link href="/login">Đăng nhập</Link></li>
              ) : (
                <li>
                  <form action={logout}>
                    <button type="submit" className="text-zinc-700 hover:text-zinc-900">Đăng xuất</button>
                  </form>
                </li>
              )}
            </ul>
          </nav>
        </header>
        <main className="mx-auto max-w-6xl px-4 py-8">{children}</main>
        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  )
}
