import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  let user: { email?: string } | null = null
  try {
    const { getSupabaseServer } = await import('@/lib/supabase-server')
    const supabase = await getSupabaseServer()
    const { data } = await supabase.auth.getUser()
    user = data?.user ?? null
  } catch {
    // Supabase not configured; render public nav only
  }

  async function logout() {
    'use server'
    const { cookies } = await import('next/headers')
    const { redirect } = await import('next/navigation')
    const store = await cookies()
    store.delete('sb-access-token')
    store.delete('sb-refresh-token')
    try {
      const { getSupabaseServer } = await import('@/lib/supabase-server')
      const supabase = await getSupabaseServer()
      await supabase.auth.signOut()
    } catch {}
    redirect('/login')
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b bg-white/70 backdrop-blur supports-[backdrop-filter]:bg-white/60">
          <nav className="mx-auto max-w-6xl px-4 py-3 w-full flex items-center justify-between">
            <Link href="/" className="font-semibold tracking-tight text-zinc-900">EduSync</Link>
            <ul className="flex gap-4 text-sm items-center">
              {user && (
                <li><Link href="/violation-entry">Nhập vi phạm</Link></li>
              )}
              {!user ? (
                <li><Link href="/login">Đăng nhập</Link></li>
              ) : (
                <li>
                  <form action={logout}>
                    <button type="submit" className="text-zinc-700 hover:text-zinc-900">Đăng xuất</button>
                  </form>
                </li>
              )}
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  )
}
