#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * Inject build version into service worker, manifest, and generated metadata.
 * Version format: <packageVersion>-<YYYYMMDD>-<shortSha?> (sha optional).
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function readJson(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  return JSON.parse(raw);
}

function writeJson(filePath, data) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function getShortSha() {
  const fromEnv = (process.env.VERCEL_GIT_COMMIT_SHA || process.env.GIT_COMMIT || '').trim();
  if (fromEnv) return fromEnv.slice(0, 7);
  try {
    const out = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    return out.slice(0, 7);
  } catch {
    return '';
  }
}

function computeBuildInfo() {
  // Single source of truth (SSOT) is the generated build-info module.
  // Inputs: package.json version + commit SHA (Vercel/Git) + environment.
  const pkg = readJson(path.join(__dirname, '..', 'package.json'));
  const baseVersion = (pkg.version || '0.0.0').toString();
  const shortSha = getShortSha();

  const env = (process.env.VERCEL_ENV || process.env.NODE_ENV || 'development').toString();
  const builtAt = new Date().toISOString();
  const version = shortSha ? `${baseVersion}-${shortSha}` : `${baseVersion}-dev`;

  return {
    version,
    baseVersion,
    commitSha: shortSha || null,
    env,
    builtAt,
  };
}

function updateServiceWorker(appVersion) {
  const swPath = path.join(__dirname, '..', 'public', 'service-worker.js');
  const swContent = fs.readFileSync(swPath, 'utf8');
  const replaced = swContent.replace(/const APP_VERSION = ['"][^'"]+['"];/, `const APP_VERSION = '${appVersion}';`);
  fs.writeFileSync(swPath, replaced);
}

function writeBuildInfoModule(buildInfo) {
  const outDir = path.join(__dirname, '..', 'configs', 'generated');
  ensureDir(outDir);
  const outPath = path.join(outDir, 'build-info.ts');

  const content = `// This file is generated by scripts/inject-version.cjs. Do not edit manually.\n\nexport type BuildInfo = {\n  version: string;\n  baseVersion: string;\n  commitSha: string | null;\n  env: string;\n  builtAt: string;\n};\n\nexport const BUILD_INFO: BuildInfo = ${JSON.stringify(buildInfo, null, 2)} as const;\n`;
  fs.writeFileSync(outPath, content, 'utf8');
}

function writeAppVersionFile(baseVersion, appVersion) {
  const publicVersionPath = path.join(__dirname, '..', 'public', 'app-version.json');
  writeJson(publicVersionPath, { base: baseVersion, version: appVersion });
}

(function run() {
  const buildInfo = computeBuildInfo();
  writeBuildInfoModule(buildInfo);
  updateServiceWorker(buildInfo.version);
  writeAppVersionFile(buildInfo.baseVersion, buildInfo.version);
  console.log(`[inject-version] version set to ${buildInfo.version} (base=${buildInfo.baseVersion}, sha=${buildInfo.commitSha || 'none'})`);
})();
